### ISSUE TITLE
Unsafe Blocks

### ISSUE THREAD

**Issue by fernviridian** [AltOS-Rust/altos-rust#62]
Deleted

**Comment by RJ-Russell** [comment]
Unsafe blocks in the peripheral module should be fairly self-explanatory since typically it pertains to bit masking values at an address.

**Comment by L0ntra** [comment]
Currently this is a list of all unsafe blocks through the code. I have yet to remove the ones that don't need to be looked at. I'm working on that now.

**Comment by L0ntra** [comment]
OK this is good to go now.
I took an additional look at the unsafe blocks in the peripheral section, and while the blocks there are simple, we should still put comments on them. Memory safety was the original premise of this project and adding comments to the unsafe blocks shows that we put thought behind their use, rather than just using them as we please.

**Comment by dnseitz** [comment]
I don't think the number of unsafe blocks in the peripheral module gives the appearance that we are using unsafe code "as we please". It's good to try and keep the amount of unsafe code to a minimum, but there are things we need to do that are _fundamentally_ unsafe in Rust's view of memory safety. Writing to an arbitrary memory address is certainly one of those things, and that's what all of these peripherals are doing since they're all memory mapped. Adding `// UNSAFE: Accessing hardware register` to every unsafe block in the peripheral module is just going to clutter up the code without adding any useful information.

**Comment by L0ntra** [comment]
I don't see how adding a short comment like that clutters up the code. We could instead make sure that file header comment. something like:
```
//... Several unsafe blocks are used throughout this file in order to access hardware registers which 
//cannot be accessed in any other way. ...
```
